### 根据资源名熔断降级
POST http://127.0.0.1:1030/commerce-sentinel-client/sentinel-fallback/get-token
Content-Type: application/json

{
  "username": "zkc",
  "password": "e087dae60e744ea80722b785a75adbb7"
}

### 根据资源名熔断降级 忽略指定异常
GET http://127.0.0.1:1030/commerce-sentinel-client/sentinel-fallback/ignore-exception?code=2
Accept: application/json