### 获取当前用户余额信息
GET http://127.0.0.1:1007/gw/commerce-account-service/balance/current-balance
Accept: application/json
commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJjb21tZXJjZS11c2VyIjoie1wiaWRcIjoxNixcInVzZXJuYW1lXCI6XCJ6a2NcIn0iLCJqdGkiOiJhMDY5ZTc4ZC0yZWFmLTRhOGUtYWNhZi04ZjQ0ZjA1ZDM5ZDIiLCJleHAiOjE2ODQwODAwMDB9.ZEx7mNXtJESVOH33znqzmRmQWjnlJhlfWGI8PmgBUMkwhxRkm1gKgsBQ8l-DjynjPvmOMSumm4dpNsqWER9JAPbYFdeDyj6U2QH8oYe8o54KAq7DZvB90WIBtM3vC7nfIH2xXpBV5nru4KNu5eVQySLFDnwbknnLFt5RNO-Nov-uS-VyOGt8zmmhmTVaGTmdbSc70vd4XqX4gy7VFV2Es9tu_gJbYUi7JbnCuRZdGpGR4_JLeAdG2cytsm7Jxvn9UIa_koE-4ciOUIIAD7mAOx0XbsikbJrVDnpe60lIzL4tXS-h0TWLnqtkJyvCCUW7IPmQ6EB9B-WUeVIoOVexRw


### 扣减用户余额
PUT http://127.0.0.1:1007/gw/commerce-account-service/balance/deduct
Content-Type: application/json
commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJjb21tZXJjZS11c2VyIjoie1wiaWRcIjoxNixcInVzZXJuYW1lXCI6XCJ6a2NcIn0iLCJqdGkiOiJhMDY5ZTc4ZC0yZWFmLTRhOGUtYWNhZi04ZjQ0ZjA1ZDM5ZDIiLCJleHAiOjE2ODQwODAwMDB9.ZEx7mNXtJESVOH33znqzmRmQWjnlJhlfWGI8PmgBUMkwhxRkm1gKgsBQ8l-DjynjPvmOMSumm4dpNsqWER9JAPbYFdeDyj6U2QH8oYe8o54KAq7DZvB90WIBtM3vC7nfIH2xXpBV5nru4KNu5eVQySLFDnwbknnLFt5RNO-Nov-uS-VyOGt8zmmhmTVaGTmdbSc70vd4XqX4gy7VFV2Es9tu_gJbYUi7JbnCuRZdGpGR4_JLeAdG2cytsm7Jxvn9UIa_koE-4ciOUIIAD7mAOx0XbsikbJrVDnpe60lIzL4tXS-h0TWLnqtkJyvCCUW7IPmQ6EB9B-WUeVIoOVexRw

{
  "userId": 16,
  "balance": 5
}