### 创建订单
POST http://127.0.0.1:1007/gw/commerce-order-service/order/create
Content-Type: application/json
Accept: application/json
commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJjb21tZXJjZS11c2VyIjoie1wiaWRcIjoxNixcInVzZXJuYW1lXCI6XCJ6a2NcIn0iLCJqdGkiOiI0NzQ2YjBjNi1iYjgxLTRiZGYtOGU1Zi1mZTRiZWIyMzdkYTIiLCJleHAiOjE2ODQ5NDQwMDB9.Coem3PkacADq1wYRn8Arg-OvAiEam6-sj-dg_U37LJXlQziu9LMrGSlQncEJqTN-N9ekcRFtnsFL8CAZrx-5aHV-_IWEsJtWPid9ZjitVk9W0hc2MU8bgTQOGK5bCKA9142B6AEKmyyxo28vkryITD5MJPL6W58d-gRv_g7X9bXvrJK6patkVvvlpKyRGiPyJok666xEWM4lVGVUF7GEAc4GOewCWX4m18nZDqQw9nsdvX3fY74uf3XARvupoUgRb1HpmDyMQTfyuXZmCyscRwR4th9v7UtXjnSTEV-WfGZk8rYe3R5BAthMOIiRC8Vd6DMg_iTk_FCvMCtD9RsecQ

{
  "userAddressId": 1,
  "orderItems": [
    {
      "goodsId": 10,
      "count": 1
    },
    {
      "goodsId": 11,
      "count": 2
    },
    {
      "goodsId": 12,
      "count": 3
    }
  ]
}


###查询订单
GET http://127.0.0.1:1007/gw/commerce-order-service/order/detail?page=1
Accept: application/json
commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJjb21tZXJjZS11c2VyIjoie1wiaWRcIjoxNixcInVzZXJuYW1lXCI6XCJ6a2NcIn0iLCJqdGkiOiI0NzQ2YjBjNi1iYjgxLTRiZGYtOGU1Zi1mZTRiZWIyMzdkYTIiLCJleHAiOjE2ODQ5NDQwMDB9.Coem3PkacADq1wYRn8Arg-OvAiEam6-sj-dg_U37LJXlQziu9LMrGSlQncEJqTN-N9ekcRFtnsFL8CAZrx-5aHV-_IWEsJtWPid9ZjitVk9W0hc2MU8bgTQOGK5bCKA9142B6AEKmyyxo28vkryITD5MJPL6W58d-gRv_g7X9bXvrJK6patkVvvlpKyRGiPyJok666xEWM4lVGVUF7GEAc4GOewCWX4m18nZDqQw9nsdvX3fY74uf3XARvupoUgRb1HpmDyMQTfyuXZmCyscRwR4th9v7UtXjnSTEV-WfGZk8rYe3R5BAthMOIiRC8Vd6DMg_iTk_FCvMCtD9RsecQ

