### eyJhbGciOiJSUzI1NiJ9.eyJjb21tZXJjZS11c2VyIjoie1wiaWRcIjoxNixcInVzZXJuYW1lXCI6XCJ6a2NcIn0iLCJqdGkiOiIwNmRmOTJjMi02MWRjLTQ1NGEtODQ0NS00OTYwYTgyNmQxOTciLCJleHAiOjE2ODUxMTY4MDB9.oIobwJq8bG3IVhph8rZv7LkrUjIBZS_5JpesOr_qruYrde0Kl3e4AO5325VVLat3DHGMdHDNGEItIA_oaeaobWqmAWMq5a85jKJ_Zc24_nQ3PwMm7Fw1IsAcFeEPZQrb_nZdtvB3ATizD_fDWhVoClq2Ist1HIMPAMbmTq2LGrYZYWKBfVsLVFPluNXh4nGm2W1AhOsq5SWnIFeWNdG5TNGUCmDg8drzu9fG5VyDDg94PcFKZhmj1KoZ9ydxi7w53tJqFbQAdgek8MFdmLRiqe_NEb-JBHpeo_IV5JHxGhv0mY951QAOglkbWpYhOk8bUjk9HepkKgnFM23dq8Atbw
### 登录
POST http://127.0.0.1:1007/gw/commerce/login
Content-Type: application/json

{
  "username": "zkc",
  "password": "e087dae60e744ea80722b785a75adbb7"
}



### 注册
POST http://127.0.0.1:1007/gw/commerce/register
Content-Type: application/json

{
  "username": "test",
  "password": "e087dae60e744ea80722b785a75adbb7"
}