### eyJhbGciOiJSUzI1NiJ9.eyJjb21tZXJjZS11c2VyIjoie1wiaWRcIjoxNixcInVzZXJuYW1lXCI6XCJ6a2NcIn0iLCJqdGkiOiJiNTM5NzIwMi05MjRlLTQxZTctYWFkMC0xZmRiNGNkNjAyNjciLCJleHAiOjE2ODUwMzA0MDB9.RFkjwtR9jfATZwc5Zjhn4hyU8deXRv-k6saN_cSMBMy3Nxpz1bbi3crWZ3YlTo4ZsqVbFFrbTjRhtRh-8f9_t4iUwQjJthuLBTzRrBavpXa8uxFjMzgT2BCnAGR8zU_okq36hoAIYTZqbxs7gid-6B2T2JfYc4ph2zECQ6Ds9BMgIGIMRPpVlwzZgse0-c0patKnIkJoqTvfujT5aHFOPclFIEGiwQoeyyPC6pDcsocnXb5UBz_9zqQMMq5PHLnBUwNyUnV78EVWaYnYz7GeZAjqnLEIQAYL44wYptAtzmDCJojznNABG-2BC3VAmsa0bjaE25SBvVx8TUOiOnDzqQ
### 登录
POST http://127.0.0.1:1007/gw/commerce/login
Content-Type: application/json

{
  "username": "zkc",
  "password": "e087dae60e744ea80722b785a75adbb7"
}



### 注册
POST http://127.0.0.1:1007/gw/commerce/register
Content-Type: application/json

{
  "username": "test",
  "password": "e087dae60e744ea80722b785a75adbb7"
}