### 登录
POST http://127.0.0.1:1007/gw/commerce/login
Content-Type: application/json

{
  "username": "zkc",
  "password": "e087dae60e744ea80722b785a75adbb7"
}

### 注册
POST http://127.0.0.1:1007/gw/commerce/register
Content-Type: application/json

{
  "username": "test",
  "password": "e087dae60e744ea80722b785a75adbb7"
}