### 查询服务实例信息  授权外的接口需要携带token
GET 127.0.0.1:1007/gw/commerce-nc/nacos-client/service-instance?serviceId=commerce-gateway
Content-Type: application/json
Accept: application/json
commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJjb21tZXJjZS11c2VyIjoie1wiaWRcIjoxNixcInVzZXJuYW1lXCI6XCJ6a2NcIn0iLCJqdGkiOiIxYzg5MzE0YS0xZWZkLTRmMDgtYTQ4Ni02ZDc3OTUyNDJkNWIiLCJleHAiOjE2ODUyMDMyMDB9.s9RRGECsKxctzCI-V0g4hEyvkhw_d82TL_xNRfJTWqEZNVVzVAxuns58ajVh_Qcms9Rqd7vXaGOkGQOSAlHlKlqKdY0GFiDcCjVBGpuqzN0i0VD5Qbg6SEQNp-PeCpFZ2YPvE41_DE7JrRyGy5pcUYshcVKad2c49qSgfkQu22ii6hqvkmXsouJY9iwFY2b-O3yxSA-Wr7MMKFBzoBETXbdlpzRHkPX9s2S72lAwhZpAoQSThRkJAlhnS0T0haf1bo9NXbLy5soWAR_RzjHJ0Mw0R0qfJPqweYAwEP7k5RGKsN4dyFSeU9o5bqkThXD08kVyeNYy3eeBXYEZCbYMog
token: test

### 查看brave 跟踪信息
GET 127.0.0.1:1007/gw/commerce-nc/brave/trace-info
Accept: application/json
commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJjb21tZXJjZS11c2VyIjoie1wiaWRcIjoxNixcInVzZXJuYW1lXCI6XCJ6a2NcIn0iLCJqdGkiOiIxYzg5MzE0YS0xZWZkLTRmMDgtYTQ4Ni02ZDc3OTUyNDJkNWIiLCJleHAiOjE2ODUyMDMyMDB9.s9RRGECsKxctzCI-V0g4hEyvkhw_d82TL_xNRfJTWqEZNVVzVAxuns58ajVh_Qcms9Rqd7vXaGOkGQOSAlHlKlqKdY0GFiDcCjVBGpuqzN0i0VD5Qbg6SEQNp-PeCpFZ2YPvE41_DE7JrRyGy5pcUYshcVKad2c49qSgfkQu22ii6hqvkmXsouJY9iwFY2b-O3yxSA-Wr7MMKFBzoBETXbdlpzRHkPX9s2S72lAwhZpAoQSThRkJAlhnS0T0haf1bo9NXbLy5soWAR_RzjHJ0Mw0R0qfJPqweYAwEP7k5RGKsN4dyFSeU9o5bqkThXD08kVyeNYy3eeBXYEZCbYMog
token: test