### 查询服务实例信息  授权外的接口需要携带token
GET 127.0.0.1:1007/gw/commerce-nc/nacos-client/service-instance?serviceId=commerce-gateway
Accept: application/json
commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJjb21tZXJjZS11c2VyIjoie1wiaWRcIjoxNyxcInVzZXJuYW1lXCI6XCJ0ZXN0XCJ9IiwianRpIjoiMmMxZTk0ZDEtZGJiZi00NzNkLWI4NWMtYzgyMTI4Yjk3MDg0IiwiZXhwIjoxNjgzODIwODAwfQ.I7Z--tAvfJ5hD0obSedcwwkPefNn_YDzWevUx1COUHf-qvvdxZ2fBvpL_szHD6rMKVfprzOHlXqCyOqo4jAtxRYaAw4wpQCUa4LDe7lq8PMcionyJ217sHDu5vqejH9ir8E4oyrluXN0wUcfomyJOd34JT3hld7KItOuw9EITwABpF9QDVQ18lbDg4FYuU1PgwISGhKDhQ9YNqK7uPmbDXXZEXxdgu4Wez9wD6kqFwxscZB6oEUwZ_Qehmqz_ezXa9nIRqzIejeGGqUMQyZJYHZdMNOXUPj3Abr8g2-m5_R-SVr1rWEm5ceNqougu1ugiD9RHYx2g9RFCzcNwz6r_Q
token: test