### 查询服务实例信息  授权外的接口需要携带token
GET 127.0.0.1:1007/gw/commerce-nc/nacos-client/service-instance?serviceId=commerce-gateway
Accept: application/json
commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJjb21tZXJjZS11c2VyIjoie1wiaWRcIjoxNixcInVzZXJuYW1lXCI6XCJ6a2NcIn0iLCJqdGkiOiIzZTQwNzVkMS02NjMwLTQ3NmMtYmIyZC0wNWZlYWE2ZmUxZjciLCJleHAiOjE2ODM5OTM2MDB9.DWETPbA8cB_-Wa4JuH_h3nk9AJrJfMIyzYwskXVhMgpEHm_uRw-yxzN1V3EnCdoOXbdLn4qj-l4P7hmx0L7XvMT7nnm3fyK7Hjr-kYyACZkxrYRgPmP-SHEsNJ-ym8xQk0zFEH-kY1Lr1GwJmZPYF9y2MAeCiMIHvFlggEFQvX-LlFAKbFM8UV9GQfLD3b0BfdKlPfhyftxLdGKsGER7pQICuY_4qsAqNcEa_bKS-mZUhj2pQUCsjiAiNAGCjgGrAgtNc2Axf7FJFEWOtV46pwL7TTVcsylPKSWlrfPv04Tazdc_MXVIRkGriotPVBuuT37YZH8SfxCpLyWVZn3cpQ
token: test